### ISSUE TITLE
wrappers for lazy loading/computing configuration in relation to other configuration

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [simplistix/configurator#7]
i have a setup where credentials are loaded from vault into the configuration,
this is done via lazy loading, so that even if there is a full configuration, only the necessary roundtrips are made

if there was a tool to have config nodes load deferred when they are used (not merged) that would be a help

**Comment by cjw296** [comment]
When providing a lazy-loaded config, what would be a nice API to let you specify that?

**Comment by RonnyPfannschmidt** [comment]
a key here is that not the "config" is lazy loaded, but rather a specific value/subtree

```yaml
# myconfig.yam
users:
   myuser:
     username: !from_vault {path: a/b, key: username}
     username: !from_vault {path: a/b, key: password}
    ```

then i would like to have something like 

```
class VaultResolver(ConfigResolver):
   path: str
   key: str

   def resolve(self, config: Config, path: Path):
      return self.config.vault_loader.value_from(self.path, self.key)
```
