### ISSUE TITLE
loading a specific "path" of a config file and/or loading multiple of them

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [simplistix/configurator#8]
i have a setup where we are using dynaconf style environment

which means that instead of
```yaml
myconfig:
   host: abc
   port: 1337
```

we have something like
```yaml
# settings.yaml
default:
  myconfig:
     port: 1337
prod:
  myconfig:
    host: danger.example.com
qe:
  myconfig:
     host: qe.hidden.example.com
```

then the full config ought to be created via something like
```py
# first rough draft, please destroy :)
def load_config(current_env="qe"):
   setting = Config.from_path("settings.yaml")
   local = Config.from_path("setting.local.yaml", optional=True)
   return merge_from_environments(configs=[settings, local], environments=["global", "default", current_env])
```
